ALTER TABLE "Book" ADD COLUMN "ownerId" INTEGER REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Book" ADD COLUMN "source" TEXT DEFAULT 'library';
ALTER TABLE "Book" ADD COLUMN "lendable" INTEGER NOT NULL DEFAULT 1;
